### ISSUE TITLE
ProcessImage throws Error on line 377 for Web SDK 3.4.4

### ISSUE THREAD

**Issue by brian-menzies** [DeepARSDK/photoedit-web-js#2]
Trying to execute the processImage() function on a photo url using the steps and examples outlined in the project, but when I use Web SDK 3.4.4 from libs/deepar.js in the zip I get an uncaught exception on line 377. You're calling "deepAR.processFrame(byteArray, image.width, image.height, false)" and the browser says deepAR isn't defined.

**Comment by brian-menzies** [comment]
If I use the alternative way listed on the project's index.html, I get an Error being thrown at deepar:18:
Uncaught TypeError: Cannot read properties of null (reading 'preProcessWithBuffer')
    at e.processFrameRawPixels (deepar.js:18:406)
    at Object.processFrame (deepar.js:361:44)
    at image.onload (PremiumVideo.js?v=202153827717796:112:21)

**Comment by dmarcinkovic** [comment]
It is confirmed to be a bug in version 3.4.4. 
It is fixed in version 4.0.0.
